.catalog: 
  name: kdm-rmq-producer 
  version: 1.0.0-SNAPSHOT # Version of the versioned template of the Catalog Entry 
  description: kmd消息生产者 # Description of the versioned template of the Catalog Entry
  uuid: kdm-rmq-producer-0 # Unique identifier to be used for upgrades. Please see note. 
  questions:
    - variable: server_port
      description: "服务端口号"
      label: "server.port"
      required: true
      default: 27001

    - variable: spring_application_name
      description: "生产者信息：如向家坝的vzdb生产者--写成 vzdb_tzl(不得含有中文) "
      label: "生产者基本信息"
      required: true
      default: "vzdb_tzl"
      type: "string"

    - variable: rtdb_type
      description: "RTDB 类型[vzdb,pi,agilor,comtop,demo,edna,magus,smartReal,rtdbc]"
      label: "与库无关类型"
      default: "vzdb"
      required: true
      type: "string"


    - variable: user_path
      description: "用户目录"
      label: "服务器用户目录"
      default: "oge"
      required: false
      type: "string"
    - variable: kafka_host
      description: "kafka消息中间件地址，不能填写127.0.0.1"
      label: "kafka.host"
      required: true
      type: "service" 
    - variable: kafka_port
      description: "kafka消息中间件端口号"
      label: "kafka.port"
      required: true
      default: 9092
      type: "int" 
  
    - variable: consul_service
      description: "consul集群服务"
      label: "consul服务"
      required: true
      type: "service"


    #实时库相关配置
    - variable: rtdb_host
      description: "选择需要连接的与库无关实时库，不能填写127.0.0.1" 
      label: "实时库地址"
      required: true 
      type: "service"
    - variable: rtdb_rule
      description: "该与库无关与实时库的编码规则 例如 EB003[0-9A-Z]{24}[^C].{3}" 
      label: "rmq与库无关编码规则"
      required: true 
      default: "EB003[0-9A-Z]{24}[^C].{3}"
      type: "string"
    - variable: rtdb_port
      description: "选择需要连接的与库无关实时库端口号" 
      label: "实时库端口号"
      required: true
      default: 22235
      type: "int"
    - variable: rtdb_user
      description: "选择需要连接的与库无关实时库用户名" 
      label: "实时库用户名"
      required: true
      default: "root"
      type: "string"
    - variable: rtdb_pwd
      description: "选择需要连接的与库无关实时库密码" 
      label: "实时库密码"
      required: true
      default: "root1234"
      type: "password"
  
kdm-rmq-producer: 
  scale: 1
