vzdb: 
  image: docker.orientge.cn:5000/oge/vzdb:latest
  ports: 
    - ${vzdb_port}:22235/tcp
    - ${vzevt_port}:22136/tcp
  # environment: 
  volumes: 
    - /home/${user_path}/oge_program/log/vzdb/:/oge/vzdb/log
    - /home/${user_path}/oge_program/vzdb/data/:/oge/vzdb/data
    - /home/${user_path}/oge_program/vzdb/model/:/oge/vzdb/model
  container_name: ${vzdb_name}